// OBJECT TYPES
OBJECT_TYPE_BOT = 'OBJECT_TYPE_BOT';
OBJECT_TYPE_TRANSACTION = 'OBJECT_TYPE_TRANSACTION';
OBJECT_TYPE_MESSAGE = 'OBJECT_TYPE_MESSAGE';
OBJECT_TYPE_BLOCK = 'OBJECT_TYPE_BLOCK';


function ObjectTypes() { };

module.exports = ObjectTypes;
