// MESSAGE CONTENT
MESSAGE_REGISTER_ASK = 'MESSAGE_REGISTER_ASK';
MESSAGE_REGISTER_OK = 'MESSAGE_REGISTER_OK';
MESSAGE_NEW_TRX = 'MESSAGE_NEW_TRX';
MESSAGE_NEW_BLOCK = 'MESSAGE_NEW_BLOCK';
MESSAGE_VOTE_ELECTED = 'MESSAGE_VOTE_ELECTED';
MESSAGE_UDPATE_BLK = 'MESSAGE_UDPATE_BLK';
MESSAGE_UDPATE_TRX = 'MESSAGE_UDPATE_TRX';
MESSAGE_CHOSEN_BLOCK = 'MESSAGE_CHOSEN_BLOCK';

function MessageTypes() { }

this.exports = MessageTypes;
